version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    command: npm run start

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    restart: always

  mongo:
    container_name: database
    image: mongo
    ports:
      - "27018:27017"
